# project.yml - The new source of truth for the QuantumLeapValidator project

name: QuantumLeapValidator
options:
  bundleIdPrefix: com.quantumleap
  deploymentTarget:
    iOS: "17.0"

targets:
  QuantumLeapValidator:
    type: application
    platform: iOS
    sources:
      # This explicitly lists all the Swift source files for the main app target.
      - path: QuantumLeapValidator
        # We must exclude the .xcodeproj directory if it exists, and Preview Content.
        excludes: 
          - "**/*.xcodeproj/**"
          - "QuantumLeapValidator/Preview Content/**"
    resources:
      # This includes the main asset catalog for the app.
      - path: QuantumLeapValidator/Assets.xcassets
    info:
      path: QuantumLeapValidator/Info.plist
      properties:
        # These are the required permissions for camera and motion.
        NSCameraUsageDescription: "QuantumLeap Validator needs camera access to provide real-time pose feedback and capture training data."
        NSMotionUsageDescription: "QuantumLeap Validator needs motion sensor access to capture IMU data for pose analysis."
        # This sets the main interface file.
        UILaunchScreen: {}
    settings:
      base:
        # Sets the target device family to iPhone.
        TARGETED_DEVICE_FAMILY: "1"
        # Enables modern SwiftUI support.
        SWIFT_UI_PREVIEW_LAUNCH_POINTS: "$(SOURCE_ROOT)/QuantumLeapValidator/Preview Content"
