# project.yml - The new source of truth for the QuantumLeapValidator project

name: QuantumLeapValidator
options:
  bundleIdPrefix: com.quantumleap
  deploymentTarget:
    iOS: "17.0"

# --- ADD ZIPFoundation DEPENDENCY ---
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.0
# ------------------------------------

targets:
  QuantumLeapValidator:
    type: application
    platform: iOS
    # --- ADD ZIPFoundation DEPENDENCY ---
    dependencies:
      - package: ZIPFoundation
    # ---------------------------
    sources:
      # This explicitly lists all the Swift source files for the main app target.
      - path: QuantumLeapValidator
        # We must exclude the .xcodeproj directory if it exists, and Preview Content.
        excludes: 
          - "**/*.xcodeproj/**"
          - "QuantumLeapValidator/Preview Content/**"
    resources:
      # This includes the main asset catalog for the app.
      - path: QuantumLeapValidator/Assets.xcassets
    info:
      path: QuantumLeapValidator/Info.plist
      properties:
        # Motion permission only - camera removed for IMU-only mode
        NSMotionUsageDescription: "QuantumLeap Validator needs motion sensor access to capture IMU data for rep counting analysis."
        # This sets the main interface file.
        UILaunchScreen: {}
    settings:
      base:
        # Sets the target device family to iPhone.
        TARGETED_DEVICE_FAMILY: "1"
        # Enables modern SwiftUI support.
        SWIFT_UI_PREVIEW_LAUNCH_POINTS: "$(SOURCE_ROOT)/QuantumLeapValidator/Preview Content"
